global:
  applicationImageTag: "1.1.0"
externalSecret:
  enabled: true

autenticacion:
  replicaCount: 3
  config:
    LOG_LEVEL: warn
    COOKIE_SECURE: "true"
    WEB_ORIGIN: http://127.0.0.1:8080
    PROMOTION_STATUS: ready
  autoscaling: {minReplicas: 3}
  resources:
    requests: {cpu: 200m, memory: 192Mi}
    limits: {cpu: "1", memory: 512Mi}
solicitudes:
  replicaCount: 3
  config: {LOG_LEVEL: warn}
  autoscaling: {minReplicas: 3}
  resources:
    requests: {cpu: 200m, memory: 192Mi}
    limits: {cpu: "1", memory: 512Mi}
catalogo:
  replicaCount: 3
  config: {LOG_LEVEL: warn}
  autoscaling: {minReplicas: 3}
  resources:
    requests: {cpu: 200m, memory: 192Mi}
    limits: {cpu: "1", memory: 512Mi}
reportes:
  replicaCount: 3
  config: {LOG_LEVEL: warn}
  autoscaling: {minReplicas: 3}
  resources:
    requests: {cpu: 200m, memory: 192Mi}
    limits: {cpu: "1", memory: 512Mi}
gateway:
  replicaCount: 3
  config: {LOG_LEVEL: warn}
  autoscaling: {minReplicas: 3}
  ingress:
    enabled: false
  resources:
    requests: {cpu: 100m, memory: 96Mi}
    limits: {cpu: 500m, memory: 256Mi}
cronJobs:
  commonConfig: {LOG_LEVEL: warn}
