{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name | quote }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      {{- with .Values.secretStore.projectID }}
      projectID: {{ . | quote }}
      {{- end }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccountRef.name | quote }}
            namespace: {{ .Values.secretStore.serviceAccountRef.namespace | quote }}
{{- end }}
